---
kind: pipeline
type: docker
name: default

steps:
  - name: npm install
    image: node:14.17.5-alpine3.14
    commands:
      - npm i --registry=https://registry.npm.taobao.org

  - name: test
    image: node:14.17.5-alpine3.14
    commands:
      - npm run test

  - name: bild
    image: node:14.17.5-alpine3.14
    commands:
      - npm run docs:build
